# Generated by Django 5.2.1 on 2025-06-01 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name department'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Name department'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.department', verbose_name='Parent department'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department_uk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.department', verbose_name='Parent department'),
        ),
    ]
